// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blwihxzzmhudhyocpujr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsd2loeHp6bWh1ZGh5b2NwdWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODc1ODksImV4cCI6MjA2Nzg2MzU4OX0.ZSOIVoWrjrJvqFZn77NhpyA9FncUGUWq80uZwqpBJLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});